//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// 艾鑫提供--为okcs.im提供获取用户所在群组、查询群组信息 接口服务
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://schemas.datacontract.org/2004/07/OKCS.PMC.Model.Model", ClrNamespace="OKCS.PMC.Model.Model1")]

namespace OKCS.PMC.Model.ViewModel
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupView", Namespace="http://schemas.datacontract.org/2004/07/OKCS.PMC.Model.ViewModel")]
    public partial class GroupView : OKCS.PMC.Model.Model1.Group
    {
        
        private bool CanExitField;
        
        private bool CanManageField;
        
        private int CreationCountField;
        
        private int DiscussCountField;
        
        private int DocumentCountField;
        
        private OKCS.PMC.Model.Model1.UserInfo LeaderField;
        
        private OKCS.PMC.Model.ViewModel.UserView[] MembersField;
        
        private int MembersCountField;
        
        private int ProjectCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanExit
        {
            get
            {
                return this.CanExitField;
            }
            set
            {
                this.CanExitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanManage
        {
            get
            {
                return this.CanManageField;
            }
            set
            {
                this.CanManageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreationCount
        {
            get
            {
                return this.CreationCountField;
            }
            set
            {
                this.CreationCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiscussCount
        {
            get
            {
                return this.DiscussCountField;
            }
            set
            {
                this.DiscussCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocumentCount
        {
            get
            {
                return this.DocumentCountField;
            }
            set
            {
                this.DocumentCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OKCS.PMC.Model.Model1.UserInfo Leader
        {
            get
            {
                return this.LeaderField;
            }
            set
            {
                this.LeaderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OKCS.PMC.Model.ViewModel.UserView[] Members
        {
            get
            {
                return this.MembersField;
            }
            set
            {
                this.MembersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MembersCount
        {
            get
            {
                return this.MembersCountField;
            }
            set
            {
                this.MembersCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjectCount
        {
            get
            {
                return this.ProjectCountField;
            }
            set
            {
                this.ProjectCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserView", Namespace="http://schemas.datacontract.org/2004/07/OKCS.PMC.Model.ViewModel")]
    public partial class UserView : OKCS.PMC.Model.Model1.UserInfo
    {
        
        private bool CanManageBackgroundField;
        
        private string ImageUrlField;
        
        private string LogOutUrlField;
        
        private string idField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanManageBackground
        {
            get
            {
                return this.CanManageBackgroundField;
            }
            set
            {
                this.CanManageBackgroundField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl
        {
            get
            {
                return this.ImageUrlField;
            }
            set
            {
                this.ImageUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogOutUrl
        {
            get
            {
                return this.LogOutUrlField;
            }
            set
            {
                this.LogOutUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
}
namespace OKCS.PMC.Model.Model1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Group", Namespace="http://schemas.datacontract.org/2004/07/OKCS.PMC.Model.Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OKCS.PMC.Model.ViewModel.GroupView))]
    public partial class Group : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CreateUserIDField;
        
        private string IDField;
        
        private string NameField;
        
        private System.DateTime PostTimeField;
        
        private string SummaryField;
        
        private string UnitIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateUserID
        {
            get
            {
                return this.CreateUserIDField;
            }
            set
            {
                this.CreateUserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PostTime
        {
            get
            {
                return this.PostTimeField;
            }
            set
            {
                this.PostTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Summary
        {
            get
            {
                return this.SummaryField;
            }
            set
            {
                this.SummaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitID
        {
            get
            {
                return this.UnitIDField;
            }
            set
            {
                this.UnitIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://schemas.datacontract.org/2004/07/OKCS.PMC.Model.Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OKCS.PMC.Model.ViewModel.UserView))]
    public partial class UserInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ActivenessField;
        
        private string DeptCodeField;
        
        private string DeptIDField;
        
        private string DeptNameField;
        
        private int DeptRankField;
        
        private string EMailField;
        
        private string ExtendedField;
        
        private string LogoField;
        
        private string MobilephoneField;
        
        private string PositionNameField;
        
        private string QQField;
        
        private string RealNameField;
        
        private int ScoreField;
        
        private string TelField;
        
        private string TokenField;
        
        private string UnitIDField;
        
        private string UnitNameField;
        
        private int UnitRankField;
        
        private int UploadFileNumField;
        
        private string UserIDField;
        
        private string UserNameField;
        
        private string WeChatField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Activeness
        {
            get
            {
                return this.ActivenessField;
            }
            set
            {
                this.ActivenessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeptCode
        {
            get
            {
                return this.DeptCodeField;
            }
            set
            {
                this.DeptCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeptID
        {
            get
            {
                return this.DeptIDField;
            }
            set
            {
                this.DeptIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeptName
        {
            get
            {
                return this.DeptNameField;
            }
            set
            {
                this.DeptNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeptRank
        {
            get
            {
                return this.DeptRankField;
            }
            set
            {
                this.DeptRankField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail
        {
            get
            {
                return this.EMailField;
            }
            set
            {
                this.EMailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extended
        {
            get
            {
                return this.ExtendedField;
            }
            set
            {
                this.ExtendedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Logo
        {
            get
            {
                return this.LogoField;
            }
            set
            {
                this.LogoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobilephone
        {
            get
            {
                return this.MobilephoneField;
            }
            set
            {
                this.MobilephoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PositionName
        {
            get
            {
                return this.PositionNameField;
            }
            set
            {
                this.PositionNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QQ
        {
            get
            {
                return this.QQField;
            }
            set
            {
                this.QQField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RealName
        {
            get
            {
                return this.RealNameField;
            }
            set
            {
                this.RealNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score
        {
            get
            {
                return this.ScoreField;
            }
            set
            {
                this.ScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel
        {
            get
            {
                return this.TelField;
            }
            set
            {
                this.TelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitID
        {
            get
            {
                return this.UnitIDField;
            }
            set
            {
                this.UnitIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitName
        {
            get
            {
                return this.UnitNameField;
            }
            set
            {
                this.UnitNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UnitRank
        {
            get
            {
                return this.UnitRankField;
            }
            set
            {
                this.UnitRankField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UploadFileNum
        {
            get
            {
                return this.UploadFileNumField;
            }
            set
            {
                this.UploadFileNumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WeChat
        {
            get
            {
                return this.WeChatField;
            }
            set
            {
                this.WeChatField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IImOkcsClient")]
public interface IImOkcsClient
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImOkcsClient/GetGroupInfos", ReplyAction="http://tempuri.org/IImOkcsClient/GetGroupInfosResponse")]
    OKCS.PMC.Model.ViewModel.GroupView[] GetGroupInfos(string userID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImOkcsClient/GetGroupInfos", ReplyAction="http://tempuri.org/IImOkcsClient/GetGroupInfosResponse")]
    System.Threading.Tasks.Task<OKCS.PMC.Model.ViewModel.GroupView[]> GetGroupInfosAsync(string userID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImOkcsClient/GetGroupMembers", ReplyAction="http://tempuri.org/IImOkcsClient/GetGroupMembersResponse")]
    OKCS.PMC.Model.Model1.UserInfo[] GetGroupMembers(string CreateUserID, string groupID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImOkcsClient/GetGroupMembers", ReplyAction="http://tempuri.org/IImOkcsClient/GetGroupMembersResponse")]
    System.Threading.Tasks.Task<OKCS.PMC.Model.Model1.UserInfo[]> GetGroupMembersAsync(string CreateUserID, string groupID);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IImOkcsClientChannel : IImOkcsClient, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ImOkcsClientClient : System.ServiceModel.ClientBase<IImOkcsClient>, IImOkcsClient
{
    
    public ImOkcsClientClient()
    {
    }
    
    public ImOkcsClientClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ImOkcsClientClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ImOkcsClientClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ImOkcsClientClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public OKCS.PMC.Model.ViewModel.GroupView[] GetGroupInfos(string userID)
    {
        return base.Channel.GetGroupInfos(userID);
    }
    
    public System.Threading.Tasks.Task<OKCS.PMC.Model.ViewModel.GroupView[]> GetGroupInfosAsync(string userID)
    {
        return base.Channel.GetGroupInfosAsync(userID);
    }
    
    public OKCS.PMC.Model.Model1.UserInfo[] GetGroupMembers(string CreateUserID, string groupID)
    {
        return base.Channel.GetGroupMembers(CreateUserID, groupID);
    }
    
    public System.Threading.Tasks.Task<OKCS.PMC.Model.Model1.UserInfo[]> GetGroupMembersAsync(string CreateUserID, string groupID)
    {
        return base.Channel.GetGroupMembersAsync(CreateUserID, groupID);
    }
}
