//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edu.Web.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupView", Namespace="http://schemas.datacontract.org/2004/07/OKCS.PMC.Model.ViewModel")]
    [System.SerializableAttribute()]
    public partial class GroupView : Edu.Web.ServiceReference1.Group {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CanExitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CanManageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreationCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiscussCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocumentCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Edu.Web.ServiceReference1.UserInfo LeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Edu.Web.ServiceReference1.UserView[] MembersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MembersCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProjectCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanExit {
            get {
                return this.CanExitField;
            }
            set {
                if ((this.CanExitField.Equals(value) != true)) {
                    this.CanExitField = value;
                    this.RaisePropertyChanged("CanExit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanManage {
            get {
                return this.CanManageField;
            }
            set {
                if ((this.CanManageField.Equals(value) != true)) {
                    this.CanManageField = value;
                    this.RaisePropertyChanged("CanManage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreationCount {
            get {
                return this.CreationCountField;
            }
            set {
                if ((this.CreationCountField.Equals(value) != true)) {
                    this.CreationCountField = value;
                    this.RaisePropertyChanged("CreationCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiscussCount {
            get {
                return this.DiscussCountField;
            }
            set {
                if ((this.DiscussCountField.Equals(value) != true)) {
                    this.DiscussCountField = value;
                    this.RaisePropertyChanged("DiscussCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocumentCount {
            get {
                return this.DocumentCountField;
            }
            set {
                if ((this.DocumentCountField.Equals(value) != true)) {
                    this.DocumentCountField = value;
                    this.RaisePropertyChanged("DocumentCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Edu.Web.ServiceReference1.UserInfo Leader {
            get {
                return this.LeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.LeaderField, value) != true)) {
                    this.LeaderField = value;
                    this.RaisePropertyChanged("Leader");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Edu.Web.ServiceReference1.UserView[] Members {
            get {
                return this.MembersField;
            }
            set {
                if ((object.ReferenceEquals(this.MembersField, value) != true)) {
                    this.MembersField = value;
                    this.RaisePropertyChanged("Members");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MembersCount {
            get {
                return this.MembersCountField;
            }
            set {
                if ((this.MembersCountField.Equals(value) != true)) {
                    this.MembersCountField = value;
                    this.RaisePropertyChanged("MembersCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjectCount {
            get {
                return this.ProjectCountField;
            }
            set {
                if ((this.ProjectCountField.Equals(value) != true)) {
                    this.ProjectCountField = value;
                    this.RaisePropertyChanged("ProjectCount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Group", Namespace="http://schemas.datacontract.org/2004/07/OKCS.PMC.Model.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Edu.Web.ServiceReference1.GroupView))]
    public partial class Group : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PostTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SummaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateUserID {
            get {
                return this.CreateUserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateUserIDField, value) != true)) {
                    this.CreateUserIDField = value;
                    this.RaisePropertyChanged("CreateUserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PostTime {
            get {
                return this.PostTimeField;
            }
            set {
                if ((this.PostTimeField.Equals(value) != true)) {
                    this.PostTimeField = value;
                    this.RaisePropertyChanged("PostTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Summary {
            get {
                return this.SummaryField;
            }
            set {
                if ((object.ReferenceEquals(this.SummaryField, value) != true)) {
                    this.SummaryField = value;
                    this.RaisePropertyChanged("Summary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitID {
            get {
                return this.UnitIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitIDField, value) != true)) {
                    this.UnitIDField = value;
                    this.RaisePropertyChanged("UnitID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://schemas.datacontract.org/2004/07/OKCS.PMC.Model.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Edu.Web.ServiceReference1.UserView))]
    public partial class UserInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActivenessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeptCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeptIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeptNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DeptRankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtendedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobilephoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PositionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QQField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RealNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UnitRankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UploadFileNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WeChatField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Activeness {
            get {
                return this.ActivenessField;
            }
            set {
                if ((this.ActivenessField.Equals(value) != true)) {
                    this.ActivenessField = value;
                    this.RaisePropertyChanged("Activeness");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeptCode {
            get {
                return this.DeptCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeptCodeField, value) != true)) {
                    this.DeptCodeField = value;
                    this.RaisePropertyChanged("DeptCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeptID {
            get {
                return this.DeptIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DeptIDField, value) != true)) {
                    this.DeptIDField = value;
                    this.RaisePropertyChanged("DeptID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeptName {
            get {
                return this.DeptNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DeptNameField, value) != true)) {
                    this.DeptNameField = value;
                    this.RaisePropertyChanged("DeptName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeptRank {
            get {
                return this.DeptRankField;
            }
            set {
                if ((this.DeptRankField.Equals(value) != true)) {
                    this.DeptRankField = value;
                    this.RaisePropertyChanged("DeptRank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extended {
            get {
                return this.ExtendedField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtendedField, value) != true)) {
                    this.ExtendedField = value;
                    this.RaisePropertyChanged("Extended");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Logo {
            get {
                return this.LogoField;
            }
            set {
                if ((object.ReferenceEquals(this.LogoField, value) != true)) {
                    this.LogoField = value;
                    this.RaisePropertyChanged("Logo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobilephone {
            get {
                return this.MobilephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.MobilephoneField, value) != true)) {
                    this.MobilephoneField = value;
                    this.RaisePropertyChanged("Mobilephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PositionName {
            get {
                return this.PositionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionNameField, value) != true)) {
                    this.PositionNameField = value;
                    this.RaisePropertyChanged("PositionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QQ {
            get {
                return this.QQField;
            }
            set {
                if ((object.ReferenceEquals(this.QQField, value) != true)) {
                    this.QQField = value;
                    this.RaisePropertyChanged("QQ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RealName {
            get {
                return this.RealNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RealNameField, value) != true)) {
                    this.RealNameField = value;
                    this.RaisePropertyChanged("RealName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel {
            get {
                return this.TelField;
            }
            set {
                if ((object.ReferenceEquals(this.TelField, value) != true)) {
                    this.TelField = value;
                    this.RaisePropertyChanged("Tel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitID {
            get {
                return this.UnitIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitIDField, value) != true)) {
                    this.UnitIDField = value;
                    this.RaisePropertyChanged("UnitID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitName {
            get {
                return this.UnitNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitNameField, value) != true)) {
                    this.UnitNameField = value;
                    this.RaisePropertyChanged("UnitName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UnitRank {
            get {
                return this.UnitRankField;
            }
            set {
                if ((this.UnitRankField.Equals(value) != true)) {
                    this.UnitRankField = value;
                    this.RaisePropertyChanged("UnitRank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UploadFileNum {
            get {
                return this.UploadFileNumField;
            }
            set {
                if ((this.UploadFileNumField.Equals(value) != true)) {
                    this.UploadFileNumField = value;
                    this.RaisePropertyChanged("UploadFileNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WeChat {
            get {
                return this.WeChatField;
            }
            set {
                if ((object.ReferenceEquals(this.WeChatField, value) != true)) {
                    this.WeChatField = value;
                    this.RaisePropertyChanged("WeChat");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserView", Namespace="http://schemas.datacontract.org/2004/07/OKCS.PMC.Model.ViewModel")]
    [System.SerializableAttribute()]
    public partial class UserView : Edu.Web.ServiceReference1.UserInfo {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CanManageBackgroundField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogOutUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanManageBackground {
            get {
                return this.CanManageBackgroundField;
            }
            set {
                if ((this.CanManageBackgroundField.Equals(value) != true)) {
                    this.CanManageBackgroundField = value;
                    this.RaisePropertyChanged("CanManageBackground");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogOutUrl {
            get {
                return this.LogOutUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.LogOutUrlField, value) != true)) {
                    this.LogOutUrlField = value;
                    this.RaisePropertyChanged("LogOutUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IImOkcsClient")]
    public interface IImOkcsClient {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImOkcsClient/GetGroupInfos", ReplyAction="http://tempuri.org/IImOkcsClient/GetGroupInfosResponse")]
        Edu.Web.ServiceReference1.GroupView[] GetGroupInfos(string groupID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImOkcsClient/GetGroupInfos", ReplyAction="http://tempuri.org/IImOkcsClient/GetGroupInfosResponse")]
        System.Threading.Tasks.Task<Edu.Web.ServiceReference1.GroupView[]> GetGroupInfosAsync(string groupID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IImOkcsClientChannel : Edu.Web.ServiceReference1.IImOkcsClient, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImOkcsClientClient : System.ServiceModel.ClientBase<Edu.Web.ServiceReference1.IImOkcsClient>, Edu.Web.ServiceReference1.IImOkcsClient {
        
        public ImOkcsClientClient() {
        }
        
        public ImOkcsClientClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImOkcsClientClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImOkcsClientClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImOkcsClientClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Edu.Web.ServiceReference1.GroupView[] GetGroupInfos(string groupID) {
            return base.Channel.GetGroupInfos(groupID);
        }
        
        public System.Threading.Tasks.Task<Edu.Web.ServiceReference1.GroupView[]> GetGroupInfosAsync(string groupID) {
            return base.Channel.GetGroupInfosAsync(groupID);
        }
    }
}
